name: "Build and Deploy"

on: [push, workflow_dispatch]

env:
  AZURE_WEBAPP_NAME: webSVF-Capstone5-AppService   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './published'   # set this to the path to your web app project, defaults to the repository root
  NETCORE_VERSION: '3.1.x'                    # set netcore version
  
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest       # May want to change ubuntu version later
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}
    
      - name: Restore
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Install dependencies with npm
        run: npm install --legacy-peer-deps
      
      - name: Publish app for deploy
        run: dotnet publish --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
    
